# Generated by Django 4.1 on 2022-08-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
